name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-go@v3

    - name: Build webmanager
      working-directory: ./webmanager
      run: npm install && npm run build
    - name: Install packr2
      run: go install github.com/gobuffalo/packr/v2/packr2@v2.8.3

    - name: Run make for linux
      run: export PATH=$PATH:$(go env GOPATH)/bin && make packr && make linux
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/linux/*/*
        tag: ${{ github.ref }}
        file_glob: true
